### PR TITLE
Claude/fix issue 892 char empty comparison

### LINKED ISSUE #892: VB -> C#: wrong result for empty char comparisation
### VB.Net input code
```vbnet
Dim testChar As Char = Nothing
Dim testResult = testChar = ""
Assert.That(testResult, "comparing null character with empty string should be true")
```

### Erroneous output
```C#
bool testResult = Conversions.ToString(testChar) == "";    

```
### Expected output
```C#
bool testResult = testChar == char.MinValue;

```
### Details
* Product in use: VS extension
* Version in use: 9.0.0.0
* Did you see it working in a previous version, which? no

### PR DESCRIPTION
**Pull request by GrahamTheCoder**
Fixes #892

### CODE REVIEW

File: CodeConverter/CSharp/BinaryExpressionConverter.cs [hunk 1]
```diff
@@ -82,11 +82,25 @@ private async Task<CSharpSyntaxNode> ConvertBinaryExpressionAsync(VBasic.Syntax.
...
-                omitConversion = true; // Already handled within for the appropriate types (rhs can become int in comparison)
+                if (lhsTypeInfo.Type?.SpecialType == SpecialType.System_Char && rhsTypeInfo.Type?.SpecialType == SpecialType.System_Char) {
+                    // Do nothing, char comparison
+                } else if (!_visualBasicEqualityComparison.OptionCompareTextCaseInsensitive &&
+                           ((lhsTypeInfo.Type?.SpecialType == SpecialType.System_Char && rhsTypeInfo.Type?.SpecialType == SpecialType.System_String && _visualBasicEqualityComparison.IsNothingOrEmpty(node.Right)) ||
+                            (rhsTypeInfo.Type?.SpecialType == SpecialType.System_Char && lhsTypeInfo.Type?.SpecialType == SpecialType.System_String && _visualBasicEqualityComparison.IsNothingOrEmpty(node.Left)))) {
+                    if (lhsTypeInfo.Type?.SpecialType == SpecialType.System_Char) {
+                        rhs = CS.SyntaxFactory.MemberAccessExpression(CS.SyntaxKind.SimpleMemberAccessExpression, CS.SyntaxFactory.PredefinedType(CS.SyntaxFactory.Token(CS.SyntaxKind.CharKeyword)), CS.SyntaxFactory.IdentifierName("MinValue"));
```
Comment (GrahamTheCoder) [inline CodeConverter/CSharp/BinaryExpressionConverter.cs]: Look like a hack to make the specific test case work rather than the general fix to the root cause
