### PR TITLE
Convert linq query comma syntax #853

### LINKED ISSUE #853: VB -> C#: Comma in FromClause of Query Syntax is not correctly identified as alternate syntax for another FromClause
### VB.Net input code
```vbnet
Public Class VisualBasicClass
Sub Main
	Dim list1 As New List(Of Integer)() From {1,2,3}
	Dim list2 As New List(Of Integer) From {2, 4,5}
	
	Dim qs = From n In list1, x In list2
			 Where x = n 
			 Select New With {x, n}

	For Each a In qs
		Console.WriteLine($"n={a.n}")
		Console.WriteLine($"x={a.x}")
	Next 
End Sub
End Class
```

### Erroneous output
```C#
using System.Collections.Generic;

public partial class VisualBasicClass
{
    public void Main()
    {
        var list1 = new List<int>() { 1, 2, 3 };
        var list2 = new List<int>() { 2, 4, 5 };
        var qs = default
#error Cannot convert QueryExpressionSyntax - see comment for details
/* Cannot convert QueryExpressionSyntax, System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at ICSharpCode.CodeConverter.CSharp.QueryConverter.ConvertFromClauseSyntaxAsync(FromClauseSyntax vbFromClause) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\QueryConverter.cs:line 0
   at ICSharpCode.CodeConverter.CSharp.QueryConverter.ConvertClausesAsync(SyntaxList`1 clauses) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\QueryConverter.cs:line 43
   at ICSharpCode.CodeConverter.CSharp.ExpressionNodeVisitor.VisitQueryExpression(QueryExpressionSyntax node) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\ExpressionNodeVisitor.cs:line 655
   at ICSharpCode.CodeConverter.CSharp.CommentConvertingVisitorWrapper.ConvertHandledAsync[T](VisualBasicSyntaxNode vbNode, SourceTriviaMapKind sourceTriviaMap) in D:\GitWorkspace\CodeConverter\CodeConverter\CSharp\CommentConvertingVisitorWrapper.cs:line 48

Input:
From n In list1, x In list2
			 Where x = n 
			 Select New With {x, n}

 */
;
        foreach (var a in qs)
        {
            Console.WriteLine($"n={a.n}");
            Console.WriteLine($"x={a.x}");
        }
    }
}
```
### Expected output
```C#
using System.Collections.Generic;

public partial class VisualBasicClass
{
    public void Main()
    {
        var list1 = new List<int>() { 1, 2, 3 };
        var list2 = new List<int>() { 2, 4, 5 };
        var qs = from n in list1
			 from x in list2
			 where x == n
			 select new { x, n };


	foreach (var a in qs)
	{
		Console.WriteLine($"n={a.n}");
		Console.WriteLine($"x={a.x}");
	}
}
```

### Details
* codeconverter.icsharpcode.net / VS extension 
* never saw it working
* Any other relevant information to the issue, or your interest in contributing a fix.

Basically in a VB.net query syntax query, the "From" can optionally be replaced with a comma. Aka inside a FromClause a CommaToken followed by a CollectionRangeVariable can be replaced with another FromeClause with the CollectionRangeVariable that follows the comma.

### PR DESCRIPTION
**Pull request by GrahamTheCoder**
Fixes #853 

Starts from test case from @jrmoreno1 but with a comma before the second clause.
The code in this area is still terrible, mostly due to not understanding the two models being converted between.

### CODE REVIEW

File: CodeConverter/CSharp/QueryConverter.cs [hunk 1]
```diff
@@ -144,19 +155,13 @@ private async Task<CSharpSyntaxNode> ConvertQuerySegmentsAsync(IEnumerable<(Queu
...
-            return subQuery != null ? SyntaxFactory.QueryExpression(fromClauseSyntax, subQuery) : fromClauseSyntax.Expression;
-        }
-
-        private async Task<CSSyntax.QueryBodySyntax> ConvertQueryWithContinuationAsync(Queue<(SyntaxList<CSSyntax.QueryClauseSyntax>, VBSyntax.QueryClauseSyntax)> querySectionsReversed, SyntaxToken reusableCsFromId)
+        private async Task<CSSyntax.QueryBodySyntax> ConvertQueryWithContinuationAsync(Queue<(SyntaxList<CSSyntax.QueryClauseSyntax>, VBSyntax.QueryClauseSyntax)> querySectionsReversed, SyntaxToken? reusableCsFromId)
         {
             if (!querySectionsReversed.Any()) return null;
             var (convertedClauses, clauseEnd) = querySectionsReversed.Dequeue();
-
+            reusableCsFromId ??= convertedClauses.OfType<CSSyntax.FromClauseSyntax>().FirstOrDefault()?.Identifier.WithoutSourceMapping();
```
Comment (GrahamTheCoder) [inline CodeConverter/CSharp/QueryConverter.cs:162]: Ideally we'd take a step back and understand how VB determines which id to select. It's possible that an up front analysis would be worthwhile to tidy this mess up.

File: CodeConverter/CSharp/QueryConverter.cs [hunk 2]
```diff
@@ -33,20 +33,25 @@ public QueryConverter(CommonConversions commonConversions, SemanticModel semanti
         public async Task<CSharpSyntaxNode> ConvertClausesAsync(SyntaxList<VBSyntax.QueryClauseSyntax> clauses)
         {
             var vbBodyClauses = new Queue<VBSyntax.QueryClauseSyntax>(clauses);
-            var vbStartClause = vbBodyClauses.Dequeue();
-            var agg = vbStartClause as VBSyntax.AggregateClauseSyntax;
-            if (agg != null) {
+            var vbStartClause = vbBodyClauses.Peek();
+            CSSyntax.FromClauseSyntax fromClauseSyntaxFromAggregate = null;
+            if (vbStartClause is VBSyntax.AggregateClauseSyntax agg) {
+                vbBodyClauses.Dequeue();
```
Comment (GrahamTheCoder) [inline CodeConverter/CSharp/QueryConverter.cs:39]: Essentially treats aggregate as a special case, then everything else (including the from clause) is handled in the main loop.
