### PR TITLE
fixed #325: 

### LINKED ISSUE #325: VB -> C#: Error converting array indexer, getting round brackets instead of squre
### Input code
```vbnet
Sub Main()
	Dim str2 = GetStrings(1)
End Sub

Function GetStrings() As String()
	Return New String() {"A", "B", "C"}
End Function
```
### Erroneous output
```csharp
public static void Main()
{
   var str2 = GetStrings(1);  // should be GetStrings()[1]
}

public static string[] GetStrings()
{
  return new string[] { "A", "B", "C" };
}
```
### Expected output
```csharp
public static void Main()
{
   var str2 = GetStrings()[1];
}

public static string[] GetStrings()
{
  return new string[] { "A", "B", "C" };
}
```
### Details
Two problems actually: 
1) Array indexing brackets become converted into round brackets, instead of square.
2) Parameterless method call empty round brackets are missing.

Version in use: 6.9.0

Interested in contributing a fix.

### LINKED ISSUE #328: VB -> C#: Null propagating index operator not converted
### Input code
```vbnet
Imports System
Imports System.Collections.Generic

Friend Class Program
    Public Shared Sub Main(ByVal args As String())
        Dim x As New Dictionary(Of String, String)
        Console.WriteLine(x?("a"))
    End Sub
End Class
```

### Erroneous output
```c#
using System.Collections.Generic;

namespace ConsoleApp4
{
    internal class Program
    {
        public static void Main(string[] args)
        {
            Dictionary<string, string> x = new Dictionary<string, string>();
            ;
#error Cannot convert ExpressionStatementSyntax - see comment for details
            /* Cannot convert ExpressionStatementSyntax, System.ArgumentNullException: Value cannot be null.
            Parameter name: node
               at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetSymbolInfoForNode(SyntaxNode node, CancellationToken cancellationToken)
               at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetSymbolInfoCore(SyntaxNode node, CancellationToken cancellationToken)
               at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitInvocationExpression(InvocationExpressionSyntax node)
               at Microsoft.CodeAnalysis.VisualBasic.Syntax.InvocationExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
               at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
               at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
               at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitInvocationExpression(InvocationExpressionSyntax node)
               at Microsoft.CodeAnalysis.VisualBasic.Syntax.InvocationExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
               at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitConditionalAccessExpression(ConditionalAccessExpressionSyntax node)
               at Microsoft.CodeAnalysis.VisualBasic.Syntax.ConditionalAccessExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
               at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
               at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
               at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitConditionalAccessExpression(ConditionalAccessExpressionSyntax node)
               at Microsoft.CodeAnalysis.VisualBasic.Syntax.ConditionalAccessExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
               at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitSimpleArgument(SimpleArgumentSyntax node)
               at Microsoft.CodeAnalysis.VisualBasic.Syntax.SimpleArgumentSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
               at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
               at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
               at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitSimpleArgument(SimpleArgumentSyntax node)
               at Microsoft.CodeAnalysis.VisualBasic.Syntax.SimpleArgumentSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
               at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.<>c__DisplayClass100_0.<ConvertArguments>b__0(ArgumentSyntax a, Int32 i)
               at System.Linq.Enumerable.<SelectIterator>d__5`2.MoveNext()
               at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
               at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.SeparatedList[TNode](IEnumerable`1 nodes)
               at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitArgumentList(ArgumentListSyntax node)
               at Microsoft.CodeAnalysis.VisualBasic.Syntax.ArgumentListSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
               at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
               at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
               at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitArgumentList(ArgumentListSyntax node)
               at Microsoft.CodeAnalysis.VisualBasic.Syntax.ArgumentListSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
               at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.ConvertArgumentListOrEmpty(ArgumentListSyntax argumentListSyntax)
               at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.VisitInvocationExpression(InvocationExpressionSyntax node)
               at Microsoft.CodeAnalysis.VisualBasic.Syntax.InvocationExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
               at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
               at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
               at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.VisitInvocationExpression(InvocationExpressionSyntax node)
               at Microsoft.CodeAnalysis.VisualBasic.Syntax.InvocationExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
               at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.MethodBodyVisitor.VisitExpressionStatement(ExpressionStatementSyntax node)
               at Microsoft.CodeAnalysis.VisualBasic.Syntax.ExpressionStatementSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
               at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
               at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.ByRefParameterVisitor.AddLocalVariables(VisualBasicSyntaxNode node)
               at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.ByRefParameterVisitor.VisitExpressionStatement(ExpressionStatementSyntax node)
               at Microsoft.CodeAnalysis.VisualBasic.Syntax.ExpressionStatementSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
               at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
               at ICSharpCode.CodeConverter.CSharp.CommentConvertingMethodBodyVisitor.ConvertWithTrivia(SyntaxNode node)
               at ICSharpCode.CodeConverter.CSharp.CommentConvertingMethodBodyVisitor.DefaultVisit(SyntaxNode node)

            Input: 
                    Console.WriteLine(x?("a"))

             */
        }
    }
}
```

### Expected output
```c#
using System.Collections.Generic;

namespace ConsoleApp4
{
    internal class Program
    {
        public static void Main(string[] args)
        {
            Dictionary<string, string> x = new Dictionary<string, string>();
            Console.WriteLine(x?["a"]);
        }
    }
}
```

### Details
Product in use: VS extension

Version in use: 6.9.0.0

### LINKED ISSUE #335: VB -> C#: DataRow.Item wrong conversion
What is happening currently is the code is loosing column names and leaving the `.Item` part on VB to C# conversion.

### Input code
```vbnet
Public Function ReadDataSet(myData As DataSet) As String
    With myData.Tables(0).Rows(0)
        Return .Item("MY_COLUMN_NAME").ToString()
    End With
End Function
```

### Erroneous output
```C#
public string ReadDataSet(DataSet myData)
{
    {
        var withBlock = myData.Tables[0].Rows[0];
        return withBlock.Item.ToString();
    }
}
```

### Expected output
```C#
public string ReadDataSet(DataSet myData)
{
    {
        var withBlock = myData.Tables[0].Rows[0];
        return withBlock["MY_COLUMN_NAME"].ToString();
    }
}
```

### Details
Product in use: both

Version in use: 6.9.0

### PR DESCRIPTION
**Pull request by dmzaharov**
### Problem

Issue #325 is rooted in the VB.NET language model, which parses (A) array element access as (B) method invocation. Because of this, difficulty of distinguishing between A and B, and rewriting the tree accordingly falls onto converter. 

### Solution
* Fixes #325
* Fixes #328
* Fixes #335 
Fix works upon existing tree rewrite mechanism of method invocation into array element access within VisitInvocationExpression routine. Logic was originally added to rewrite VB's imaginary member .Item() into array access. Issue #325 appears of similar nature. Proposed fix extends utility method  TryGetElementAccessExpressionToConvert with another expression rewrite candidate selection criteria, and lets existing rewrite logic complete the work.

* Added new test MethodCallArrayIndexerBrackets
* All tests pass, except 4 solution/project-related that were failing before

### CODE REVIEW

**Comment by GrahamTheCoder** [comment]
Thanks for this. Looks on the right track, I'll have a closer look now.

**Comment by GrahamTheCoder** [comment]
I noticed some cases that were still broken so I added more tests. In order to make them pass I went in search of how the VB compiler deals with this sort of pain and discovered the Operation API. The tests now pass using that.

Do you want to try writing some other tests to try and break it? e.g. cases that would hit one of the early return statements in `VisitMemberAccessExpression` thus missing the logic I added, or cases that use property indexers or dictionaries that aren't really tested yet. I'm keen to get this logic pretty solid since it's had a few iterations already that weren't quite right.

**Comment by GrahamTheCoder** [comment]
> Issue #325 appears of similar nature

That was the issue you raised and had already mentioned. Is there another issue you've seen that's related?

**Comment by dmzaharov** [comment]
New element access logic appears solid. I could only break it by accessing a dictionary by indexer, when dictionary was declared at class level by using implicit type declaration (option infer on). But it starts working, after dictionary type is declared explicitly. I think problem is unrelated to this issue, but to picking of correct type when option Infer On is used. Also conversion of VB Chr() to native C# casting does not always work. Would you like me to create new issues or just add test cases?

**Comment by dmzaharov** [comment]
Sorry closed pull request by accident...now reopened...

**Comment by GrahamTheCoder** [comment]
Sorry I got a bit carried away in the rewrite - once I'd understood the insight you'd had into how VB parses things I realized there must be an implementation already in the roslyn API and figured that would let me delete a whole bunch of code. Thanks for the test. I'm busy for a few days so do you want to fix the production code to make it pass?

**Comment by GrahamTheCoder** [comment]
The chr issue you saw might be this one just raised https://github.com/icsharpcode/CodeConverter/issues/331
Let's have a go at fixing this issue on this PR but if it's proving tricky move it out separately if it's not a regression

**Comment by GrahamTheCoder** [comment]
^ Another test case we should add here

File: Tests/CSharp/ExpressionTests.cs [hunk 1]
```diff
@@ -604,6 +605,129 @@ public void Test()
 }");
         }
 
+        [Fact]
+        public void MethodCallDictionaryAccessConditional()
+        {
+            TestConversionVisualBasicToCSharp(@"Public Class A
+    Public Sub Test()
+        Dim dict = New Dictionary(Of String, String) From {{""a"", ""AAA""}, {""b"", ""bbb""}}
+        Dim v = dict?.Item(""a"")
```
Comment (mrmonday) [inline Tests/CSharp/ExpressionTests.cs]: I don't see a test case for plain `?("a")`, without the `Item` anywhere?

Shouldn't make a difference, but better to explicitly test it?
